### ISSUE TITLE
Configuration block unitialized constant error

### ISSUE THREAD

**Issue by evio-fragoso** [arturcp/postgresql-backup#3]
After installing the gem and adding the initializer for configuration the following error is raised: 

![constant error](https://user-images.githubusercontent.com/98324568/178256282-63087a01-6bd5-4a49-9749-cebba77c95c3.png)

I tried to change versions without success. I'm using ruby 2.7.6 and rails 6.1.4

**Comment by arturcp** [comment]
Thanks for reporting this, @evio-fragoso, I will take a closer look to understand what is going on

**Comment by arturcp** [comment]
@evio-fragoso can you try to require `postgresql_backup` in the first line of your initializer? I created a new rails project with the versions you use and this line solved the problem:

```
require 'postgresql_backup'

PostgresqlBackup.configure do |config|
  # This gem works with two possible repositories:
  ...
```

Let me know if the issue is gone with that, so I can update the README

**Comment by evio-fragoso** [comment]
@arturcp it worked after requiring in this files. Thank you!
